### ISSUE TITLE
Add esbuild

### ISSUE THREAD

**Issue by simon04** [FlorianRappl/bundler-comparison#2]
Very interesting comparison, thank you!

Could you add esbuild to your comparison, please? https://esbuild.github.io/

**Comment by FlorianRappl** [comment]
Yeah I know esbuild, but unfortunately it does not qualify yet. It cannot handle SASS (or CSS in general) and HTML. Since it does not have a plugin ecosystem the functionality cannot be added.

Once esbuild has matured and can be considered a full app bundler (not just an ES bundler) this may change.

**Comment by simon04** [comment]
Work-in-progress support for CSS is provided, see https://esbuild.github.io/content-types/#css

**Comment by FlorianRappl** [comment]
That's great! How about SASS?

The dependencies of these comparison are:

- TypeScript
- SASS
- React with React DOM

So I think (1) and (3) are not a problem. Again (2) would be needed. The HTML part is optional.
